sudo: required
dist: trusty
language: generic
cache:
  ccache: true
  directories:
    - $HOME/.ccache
git:
  depth: 1
  submodules: false
services:
  - docker
notifications:
  email:
    - travis@codelabs.ch
env:
  global:
    - CCACHE_HOST=$HOME/.ccache
    - CCACHE_DOCKER=/home/user/.ccache
    - DOCKER_IMG=codelabsch/muen-dev-env
    - DOCKER_CACHE_BRANCH=devel
    - BUILD_OUTPUT_VERBOSE=1
    - BUILD_OUTPUT_SYNC=line
install:
  - git config --file=.gitmodules submodule.components/linux/src.url https://git.codelabs.ch/muen/linux.git
  - git config --file=.gitmodules submodule.components/tau0-static.url https://git.codelabs.ch/muen/tau0.git
  - git config --file=.gitmodules submodule.tools/mugenschedcfg.url https://git.codelabs.ch/muen/mugenschedcfg.git
  - git config --file=.gitmodules submodule.components/libxhcidbg.url https://git.codelabs.ch/libxhcidbg.git
  - git config --file=.gitmodules submodule.components/linux/modules/muenfs.url https://git.codelabs.ch/muen/linux/muenfs.git
  - git config --file=.gitmodules submodule.components/linux/modules/muennet.url https://git.codelabs.ch/muen/linux/muennet.git
  - git config --file=.gitmodules submodule.components/linux/modules/muenblock.url https://git.codelabs.ch/muen/linux/muenblock.git
  - git submodule update --init --depth=1
  - sudo sh -c 'echo "max_size = 2.0G" > ${CCACHE_HOST}/ccache.conf'
  - sudo chown -R 1000:1000 ${CCACHE_HOST}
  - sudo chown -R 1000:1000 ${TRAVIS_BUILD_DIR}
  - df -alh
  - ccache -z
  - DOCKER_PULL() { docker pull
    ${DOCKER_IMG}:${DISTRO_NAME}-${DISTRO_VERSION}_muen-${DOCKER_CACHE_BRANCH} || true;
    }
  - DOCKER_BUILD() { docker build
    --cache-from ${DOCKER_IMG}:${DISTRO_NAME}-${DISTRO_VERSION}_muen-${DOCKER_CACHE_BRANCH}
    --build-arg distro_name=${DISTRO_NAME}
    --build-arg distro_version=${DISTRO_VERSION}
    --tag ${DOCKER_IMG}:run
    --tag ${DOCKER_IMG}:latest
    --tag ${DOCKER_IMG}:${DISTRO_NAME}-${DISTRO_VERSION}_muen-${TRAVIS_BRANCH}
    -f tools/docker/Dockerfile.muen-dev-env .;
    }
  - DOCKER_PUSH() {
    if [ "$TRAVIS_BRANCH" = "master" ] || [ "$TRAVIS_BRANCH" = "devel" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker push ${DOCKER_IMG}:${DISTRO_NAME}-${DISTRO_VERSION}_muen-${TRAVIS_BRANCH};
    if [ "$TRAVIS_BRANCH" = "devel" ] && [ "$DISTRO_NAME" = "debian" ]; then
    docker push ${DOCKER_IMG}:latest;
    fi
    fi
    }
  - DOCKER_RUN() { docker run
    -v ${CCACHE_HOST}:${CCACHE_DOCKER}
    -v ${TRAVIS_BUILD_DIR}:/mnt
    -e BUILD_OUTPUT_VERBOSE=${BUILD_OUTPUT_VERBOSE}
    -e BUILD_OUTPUT_SYNC=${BUILD_OUTPUT_SYNC}
    -w /mnt
    ${DOCKER_IMG}:run
    /bin/sh -c "make -j2 iso && ccache -s && df -alh";
    }
jobs:
  include:
    - stage: Build on debian and ubuntu
      script:
        - export DISTRO_NAME=debian
        - export DISTRO_VERSION=buster
        - DOCKER_PULL
        - DOCKER_BUILD
        - DOCKER_PUSH
        - DOCKER_RUN
    - script:
        - export DISTRO_NAME=ubuntu
        - export DISTRO_VERSION=bionic
        - DOCKER_PULL
        - DOCKER_BUILD
        - DOCKER_PUSH
        - DOCKER_RUN
